--DELETE FROM m_to_n_dev.student;
INSERT INTO m_to_n_dev.student (first_name,sur_name) 
VALUES 
  ('Ava','Wilson'),
  ('Harry','Taylor'),
  ('Olivia','Brown'),
  ('Michael','Garcia'),
  ('Harper','Moore'),
  ('Isabella','Wilson'),
  ('Alexander','Wilson'),
  ('Ethan','Thompson'),
  ('Emily','Hernandez'),
  ('Emma','Hernandez'),
  ('Michael','White'),
  ('Ava','Anderson'),
  ('Noah','Thomas'),
  ('Harry','Garcia'),
  ('Emma','Smith'),
  ('Isabella','Anderson'),
  ('Isabella','Martinez'),
  ('Noah','Thompson'),
  ('Ava','Taylor'),
  ('Sophia','Wilson'),
  ('Alexander','Williams'),
  ('Ava','Johnson'),
  ('Alexander','Jones'),
  ('Harper','Moore'),
  ('Ethan','Davis'),
  ('Isabella','Taylor'),
  ('Olivia','Martin'),
  ('Ethan','Martin'),
  ('George','Thomas'),
  ('Alexander','Brown'),
  ('Mia','Wilson'),
  ('Oliver','Rodriguez'),
  ('Ava','Anderson'),
  ('Charlotte','Miller'),
  ('Charlotte','Garcia'),
  ('Harry','Garcia'),
  ('Isabella','Anderson'),
  ('Charlie','Smith'),
  ('Emma','Smith'),
  ('Sophia','Anderson'),
  ('Ethan','Garcia'),
  ('Isabella','Wilson'),
  ('Jacob','Miller'),
  ('Olivia','White'),
  ('Alexander','Williams'),
  ('Ava','Jackson'),
  ('Ethan','Davis'),
  ('Oliver','White'),
  ('Sophia','Taylor'),
  ('Harry','Moore'),
  ('Ethan','Martin'),
  ('Alexander','Thompson'),
  ('Alexander','Brown'),
  ('Amelia','Hernandez'),
  ('Harry','Anderson'),
  ('Harry','Wilson'),
  ('Noah','Rodriguez'),
  ('Harry','Martinez'),
  ('Emma','Brown'),
  ('Harry','Taylor'),
  ('Jacob','Martinez'),
  ('Michael','Thompson'),
  ('Harper','Davis'),
  ('Alexander','Rodriguez'),
  ('Harry','White'),
  ('Jack','Martin'),
  ('Jacob','Hernandez'),
  ('Olivia','Jackson'),
  ('Charlotte','Davis'),
  ('Harry','Davis'),
  ('Oliver','Johnson'),
  ('Emma','Moore'),
  ('Charlotte','Martin'),
  ('Isabella','Smith'),
  ('Harry','Martin'),
  ('Emma','Rodriguez'),
  ('Michael','Moore'),
  ('Mia','Anderson'),
  ('Olivia','Williams'),
  ('Alexander','Garcia'),
  ('Charlie','Thomas'),
  ('Jack','Martinez'),
  ('Harper','Wilson'),
  ('Oliver','Williams'),
  ('Amelia','Jackson'),
  ('Mia','Johnson'),
  ('Jack','Smith'),
  ('Jack','Taylor'),
  ('Emma','Hernandez'),
  ('Olivia','Brown'),
  ('Charlie','Miller'),
  ('Emily','Martinez'),
  ('Jack','White'),
  ('Ethan','Smith'),
  ('Noah','Martinez'),
  ('Isabella','Miller'),
  ('Isabella','Garcia'),
  ('Sophia','Brown'),
  ('Mia','Williams'),
  ('Jacob','Jackson'),
  ('Noah','Jackson'),
  ('Noah','White'),
  ('Alexander','Martinez'),
  ('Olivia','Rodriguez'),
  ('Harry','Williams'),
  ('Olivia','Jones'),
  ('Ethan','Jones'),
  ('Ethan','Thomas'),
  ('Charlie','Wilson'),
  ('Noah','Williams'),
  ('Oliver','Thomas'),
  ('Ava','Wilson'),
  ('Harper','Smith'),
  ('Charlie','Taylor'),
  ('Ava','Hernandez'),
  ('Jacob','Brown'),
  ('Charlie','Jackson'),
  ('Oliver','Brown'),
  ('Charlie','Davis'),
  ('Amelia','Jones'),
  ('Ava','White'),
  ('Isabella','Hernandez'),
  ('Michael','Johnson'),
  ('George','Jones'),
  ('George','Williams'),
  ('Ethan','Moore'),
  ('Mia','Thomas'),
  ('Jack','Jones'),
  ('Amelia','Brown'),
  ('Ethan','Rodriguez'),
  ('George','Brown'),
  ('Oliver','Rodriguez'),  
  ('Mia','Garcia');
--SELECT * FROM m_to_n_dev.student;
 
--DELETE FROM m_to_n_dev.course;
INSERT INTO m_to_n_dev.course (subject,name)
VALUES 
  ('Chemical Engineering','Process operations – reactors, separators, biotechnology'),
  ('Chemical Engineering','Principles of Chemical Engineering'),
  ('Electrical Engineering','The Future of Electrical Engineering'),
  ('Medicine','The Essence of Medicine'),
  ('Literature','Applications of Literature'),
  ('Biology','Advanced Biology'),
  ('Mechanical Engineering','The World of Mechanical Engineering'),
  ('Electrical Engineering','Fundamentals of Electrical Engineering'),
  ('Physics','Introduction to Physics'),
  ('Physics','The Challenge of Physics'),
  ('Electrical Engineering','Introduction to Electrical Engineering'),
  ('Literature','Introduction to Literature'),
  ('Chemical Engineering','Introduction to Chemical Engineering'),
  ('Medicine','Advanced Medicine'),
  ('Medicine','Principles of Medicine'),
  ('Physics','Introduction to Physics'),
  ('Physics','Principles of Physics'),
  ('Chemical Engineering','The Future of Chemical Engineering'),
  ('Medicine','The Future of Medicine'),
  ('Electrical Engineering','The Challenge of Electrical Engineering'),
  ('Electrical Engineering','Exploring the Electrical Engineering'),
  ('Computer Science','Introduction to Computer Science'),
  ('Physics','The Future of Physics'),
  ('Chemical Engineering','Advanced Chemical Engineering'),
  ('Biology','Introduction to Biology'),
  ('Medicine','The Challenge of Medicine'),  
  ('Chemical','Process systems – safety, economics');
--SELECT * FROM m_to_n_dev.course;
 
--DELETE FROM m_to_n_dev.student_course_mappings;
INSERT INTO m_to_n_dev.student_course_mappings (student_id, course_id)
VALUES 
  (1, 1),
  (1, 2),
  (2, 5),
  (2, 1),
  (5, 1),  
  (1, 3),
  (1, 4),
  (1, 5),
  (2, 2),
  (2, 3),
  (3, 2),
  (2, 3),  
  (4, 2),
  (6, 1),
  (7, 1),
  (10, 2),
  (11, 2),
  (12, 2),
  (13, 2),
  (14, 1),
  (14, 2),
  (14, 3),
  (14, 4),
  (14, 5),
  (14, 6),
  (14, 7),
  (14, 8),
  (14, 9);
--SELECT * FROM m_to_n_dev.student_course_mappings;


